import { AlertTriangle, Check, Clock3, Database, RefreshCw, ShieldX } from 'lucide-react'
import type { Candidate, HospitalCandidate } from '../lib/api'
import './decision-state.css'

export type ViewState = 'idle' | 'loading' | 'success' | 'error' | 'stale'
type Props = { title: string; candidates: (Candidate | HospitalCandidate)[]; state: ViewState; kind: 'ambulance' | 'hospital'; selectedCode?: string; onSelect: (candidate: Candidate | HospitalCandidate) => void; onRetry?: () => void }

export function CandidateList({ title, candidates, state, kind, selectedCode, onSelect, onRetry }: Props) {
  if (state === 'loading') return <div className="candidate-state" role="status" aria-live="polite" aria-label={`${title} loading`}><div className="skeleton-row" /><div className="skeleton-row" /><div className="state-caption"><RefreshCw aria-hidden="true" className="spin" size={14} /> Analyzing compatible {kind}s...</div></div>
  if (state === 'error') return <div className="candidate-state error" role="alert"><AlertTriangle size={21} /><strong>Matching service unavailable</strong><span>We could not retrieve a fresh recommendation. No assignment can be confirmed from an unavailable service.</span>{onRetry && <button type="button" onClick={onRetry}>Retry</button>}</div>
  if (state === 'stale') return <div className="candidate-state stale" role="status" aria-live="polite"><Clock3 aria-hidden="true" size={21} /><strong>Showing stale recommendations</strong><span>Last known results are not confirmation. Refresh before assigning a resource.</span></div>
  if (state === 'idle') return <div className="candidate-state"><Database size={21} /><strong>Waiting for input</strong><span>Complete the previous step to evaluate candidates.</span></div>
  return <div className="candidate-list"><div className="candidate-list-heading"><span>{title}</span><span>{candidates.length} SCANNED · {candidates.filter((candidate) => candidate.eligible).length} ELIGIBLE</span></div>{candidates.map((candidate) => <CandidateRow key={candidate.code} candidate={candidate} kind={kind} selected={candidate.code === selectedCode} onSelect={onSelect} />)}</div>
}

function CandidateRow({ candidate, kind, selected, onSelect }: { candidate: Candidate | HospitalCandidate; kind: 'ambulance' | 'hospital'; selected: boolean; onSelect: (candidate: Candidate | HospitalCandidate) => void }) {
  const title = candidate.code; const meta = kind === 'ambulance' ? `${Math.round((candidate.eta_s ?? 0) / 60)} min ETA` : `${Math.round((candidate.eta_s ?? 0) / 60)} min ETA`; const reasons = candidate.reasons.map((reason) => reason.replaceAll('_', ' '))
  return <article className={`candidate-card ${candidate.eligible ? 'eligible' : 'ineligible'} ${selected ? 'selected' : ''}`}><div className="candidate-rank">{candidate.eligible ? `0${candidate.rank ?? '-'}` : '—'}</div><div className="candidate-main"><strong>{title} {candidate.eligible && <span aria-label="eligible"><Check size={14} /></span>}</strong><p>{kind === 'ambulance' ? 'ALS response unit' : 'Simulated Hospital Network'} · {meta}</p>{candidate.eligible ? <div className="candidate-meta"><span className="mini-tag">{kind === 'ambulance' ? 'CAPABILITY OK' : 'CAPACITY VERIFIED'}</span><span className="mini-tag"><Clock3 size={10} /> {candidate.age_s ?? 8}s old</span><span className="mini-tag">{candidate.data_mode ?? 'SIMULATED'}</span></div> : <div className="candidate-reasons">{reasons.map((reason) => <span className="reason-tag" key={reason}><ShieldX size={10} /> {reason}</span>)}</div>}</div>{candidate.eligible && <button className="candidate-action" type="button" onClick={() => onSelect(candidate)} disabled={selected}>{selected ? 'SELECTED' : 'SELECT'}</button>}</article>
}

export function ResourceCard({ state, resource = 'ICU' }: { state: ViewState; resource?: string }) { if (state === 'loading') return <div className="resource-card-state"><RefreshCw className="spin" size={16} /> Checking {resource} capacity...</div>; if (state === 'error') return <div className="resource-card-state error" role="alert"><AlertTriangle size={16} /> Resource data unavailable. Unknown is not available.</div>; if (state === 'stale') return <div className="resource-card-state stale"><Clock3 size={16} /> {resource} reading is stale and cannot be confirmed.</div>; return <div className="resource-card-state"><Check size={16} /> {resource} capacity verified · simulated</div> }
