from enum import StrEnum


class Role(StrEnum):
    DISPATCHER = "DISPATCHER"
    AMBULANCE_CREW = "AMBULANCE_CREW"
    HOSPITAL_STAFF = "HOSPITAL_STAFF"
    HOSPITAL_ADMIN = "HOSPITAL_ADMIN"
    SYSTEM_ADMIN = "SYSTEM_ADMIN"
    DEMO_CONTROLLER = "DEMO_CONTROLLER"


class IncidentStatus(StrEnum):
    CREATED = "CREATED"
    ANALYZING = "ANALYZING"
    DISPATCHED = "DISPATCHED"
    HOSPITAL_SELECTED = "HOSPITAL_SELECTED"
    ACCEPTED = "ACCEPTED"
    RESOURCE_RESERVED = "RESOURCE_RESERVED"
    IN_TRANSIT = "IN_TRANSIT"
    ARRIVED = "ARRIVED"
    HANDOVER = "HANDOVER"
    COMPLETED = "COMPLETED"
    ESCALATED = "ESCALATED"
    CANCELLED = "CANCELLED"


class MissionStatus(StrEnum):
    CREATED = "CREATED"
    ASSIGNED = "ASSIGNED"
    EN_ROUTE_TO_PATIENT = "EN_ROUTE_TO_PATIENT"
    ON_SCENE = "ON_SCENE"
    PATIENT_ON_BOARD = "PATIENT_ON_BOARD"
    EN_ROUTE_TO_HOSPITAL = "EN_ROUTE_TO_HOSPITAL"
    ARRIVED = "ARRIVED"
    HANDOVER = "HANDOVER"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"
    FAILED = "FAILED"
    REASSESSMENT = "REASSESSMENT"


class RequirementLevel(StrEnum):
    REQUIRED = "REQUIRED"
    PREFERRED = "PREFERRED"
    UNKNOWN = "UNKNOWN"


class AmbulanceStatus(StrEnum):
    AVAILABLE = "AVAILABLE"
    RESERVED = "RESERVED"
    DISPATCHED = "DISPATCHED"
    UNAVAILABLE = "UNAVAILABLE"
    MAINTENANCE = "MAINTENANCE"


class HospitalStatus(StrEnum):
    ACTIVE = "ACTIVE"
    LIMITED = "LIMITED"
    TEMPORARILY_UNAVAILABLE = "TEMPORARILY_UNAVAILABLE"
    CLOSED = "CLOSED"
    UNKNOWN = "UNKNOWN"


class ResourceStatus(StrEnum):
    ACTIVE = "ACTIVE"
    INACTIVE = "INACTIVE"


class AcceptanceStatus(StrEnum):
    PENDING = "PENDING"
    ACCEPTED = "ACCEPTED"
    REJECTED = "REJECTED"
    EXPIRED = "EXPIRED"
    CANCELLED = "CANCELLED"


class ReservationStatus(StrEnum):
    HELD = "HELD"
    CONFIRMED = "CONFIRMED"
    IN_USE = "IN_USE"
    RELEASED = "RELEASED"
    EXPIRED = "EXPIRED"
    CANCELLED = "CANCELLED"


class DataMode(StrEnum):
    SIMULATED = "SIMULATED"
    LIVE = "LIVE"
